# Generated by Django 3.2.16 on 2022-10-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.CharField(max_length=100)),
                ('t_text', models.TextField()),
                ('t_username', models.CharField(max_length=100)),
                ('t_nickname', models.CharField(max_length=100)),
                ('t_likes', models.IntegerField()),
                ('t_retweets', models.IntegerField()),
                ('t_followers', models.IntegerField()),
                ('t_verified', models.BooleanField()),
                ('t_date', models.DateTimeField()),
            ],
        ),
    ]
