# Generated by Django 3.2.16 on 2022-10-12 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TweetSearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_hashtag', models.CharField(max_length=50)),
                ('h_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TweetSearch.tweet')),
            ],
        ),
    ]
