# Generated by Django 4.1.2 on 2022-10-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TweetSearch', '0002_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='t_hashtags',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
    ]
